import streamlit as st
import requests
import urllib.parse
import random

# --- Functions ---

def generate_text_pollinations(prompt):
    """
    Generates text using Pollinations.ai (No API Key needed).
    This bypasses Google's 429 Quota errors.
    """
    try:
        # 1. Clean the prompt for URL
        clean_prompt = urllib.parse.quote(f"Write a short, viral caption for: {prompt}")
        
        # 2. Call the API (It works like a web browser)
        url = f"https://text.pollinations.ai/{clean_prompt}"
        
        # 3. Get the raw text
        response = requests.get(url)
        return response.text
        
    except Exception as e:
        return f"Error: {e}"

def get_image_url(prompt):
    """
    Generates a valid Pollinations Image URL.
    Fixes the 'broken image' icon by properly encoding the text.
    """
    # 1. URL Encode the prompt (Essential for complex prompts)
    encoded_prompt = urllib.parse.quote(prompt)
    
    # 2. Add random seed to force a new image every time
    seed = random.randint(1, 99999)
    
    # 3. Construct the URL (Using Flux model for quality)
    image_url = f"https://image.pollinations.ai/prompt/{encoded_prompt}?width=1024&height=1024&seed={seed}&model=flux&nologo=true"
    
    return image_url

# --- Streamlit UI ---

st.set_page_config(page_title="No-Limit AI Studio", page_icon="🔓")

st.title("🔓 No-Limit AI Studio")
st.markdown("Unlimited Text & Images. **No API Keys Required.**")

user_prompt = st.text_input("Enter content idea:", placeholder="e.g., A cyberpunk samurai eating ramen")

if st.button("Generate Content"):
    if not user_prompt:
        st.warning("Please enter a prompt!")
    else:
        st.info("🚀 Generating (This is 100% Free & Unlimited)...")
        
        col1, col2 = st.columns(2)

        # 1. TEXT (Pollinations)
        with st.spinner("Writing Caption..."):
            caption = generate_text_pollinations(user_prompt)
            if caption:
                st.success("✅ Caption Ready")
                st.markdown(f"### 📢 {caption}")
            else:
                st.error("Text Generation Failed.")

        # 2. IMAGE (Pollinations)
        with st.spinner("Generating Image..."):
            img_url = get_image_url(user_prompt)
            
            with col1:
                # Display the image from the URL
                st.image(img_url, caption="Generated by Pollinations (Flux)", use_container_width=True)
                
                # Backup Link: If the image fails to load in the app, this button opens it
                st.link_button("⬇️ Download / Open Image", img_url)
            
            st.success("✅ Image Ready")
