import streamlit as st
import google.generativeai as genai
import time

# --- Configuration ---
if "GOOGLE_API_KEY" in st.secrets:
    genai.configure(api_key=st.secrets["GOOGLE_API_KEY"])
else:
    st.error("Missing GOOGLE_API_KEY in secrets. Please add it!")
    st.stop()

# --- Functions ---

def generate_text_gemini(prompt):
    """
    Tries multiple Gemini models to find one that works.
    """
    # List of likely available models in 2026
    models_to_try = ['gemini-2.0-flash', 'gemini-1.5-flash', 'gemini-pro']
    
    for model_name in models_to_try:
        try:
            model = genai.GenerativeModel(model_name)
            response = model.generate_content(
                f"Write a single, viral, punchy caption (under 15 words) for this image idea: {prompt}"
            )
            return response.text.strip()
        except Exception:
            continue # Try the next model
            
    return "Error: Could not connect to Gemini. Check your API Key."

def get_pollinations_image_url(prompt):
    """
    Generates a direct image URL using Pollinations.ai.
    This is 100% free, requires no key, and never runs out of credits.
    """
    # We clean the prompt to make it URL-safe
    clean_prompt = prompt.replace(" ", "%20")
    # We add a random seed to make sure we get a new image every time
    seed = int(time.time())
    
    url = f"https://pollinations.ai/p/{clean_prompt}?width=1080&height=1620&seed={seed}&model=flux"
    return url

# --- Streamlit UI ---

st.set_page_config(page_title="Forever Free AI", page_icon="♾️")

st.title("♾️ The Forever Free Studio")
st.markdown("Images via **Pollinations** (Unlimited) | Text via **Gemini**")

user_prompt = st.text_input("Enter your idea:", placeholder="e.g., A cyberpunk cat eating noodles")

if st.button("Generate"):
    if not user_prompt:
        st.warning("Please enter a prompt!")
    else:
        col1, col2 = st.columns([1, 1])
        
        # 1. Image (Pollinations - Instant & Free)
        with col1:
            with st.spinner("Generating Image..."):
                # We just get the URL - the browser does the work!
                image_url = get_pollinations_image_url(user_prompt)
                st.image(image_url, caption="Generated by Pollinations.ai", use_container_width=True)
                st.success("✅ Image Ready")

        # 2. Text (Gemini)
        with col2:
            with st.spinner("Writing Caption..."):
                caption = generate_text_gemini(user_prompt)
                st.markdown(f"### 📢 Caption")
                st.info(caption)
                if "Error" not in caption:
                    st.success("✅ Text Ready")
