import streamlit as st
import requests
import urllib.parse
import random
import io

# --- Functions ---

def generate_text_pollinations(prompt):
    """
    Generates text using Pollinations.ai (No API Key needed).
    """
    try:
        clean_prompt = urllib.parse.quote(f"Write a short, viral caption for: {prompt}")
        url = f"https://text.pollinations.ai/{clean_prompt}"
        response = requests.get(url)
        return response.text
    except Exception as e:
        return f"Error: {e}"

def get_image_url(prompt):
    """
    Generates a valid Pollinations Image URL.
    """
    encoded_prompt = urllib.parse.quote(prompt)
    seed = random.randint(1, 99999)
    image_url = f"https://image.pollinations.ai/prompt/{encoded_prompt}?width=1024&height=1024&seed={seed}&model=flux&nologo=true"
    return image_url

def download_image(url):
    """
    Downloads the image bytes so we can create a download button.
    """
    try:
        response = requests.get(url)
        response.raise_for_status() # Check for errors
        return response.content
    except Exception as e:
        return None

# --- Streamlit UI ---

st.set_page_config(page_title="No-Limit AI Studio", page_icon="🔓")

st.title("🔓 No-Limit AI Studio")
st.markdown("Unlimited Text & Images. **No API Keys Required.**")

user_prompt = st.text_input("Enter content idea:", placeholder="e.g., A cyberpunk samurai eating ramen")

if st.button("Generate Content"):
    if not user_prompt:
        st.warning("Please enter a prompt!")
    else:
        st.info("🚀 Generating (This is 100% Free & Unlimited)...")
        
        col1, col2 = st.columns(2)

        # 1. TEXT (Pollinations)
        with st.spinner("Writing Caption..."):
            caption = generate_text_pollinations(user_prompt)
            if caption:
                st.success("✅ Caption Ready")
                st.markdown(f"### 📢 {caption}")
            else:
                st.error("Text Generation Failed.")

        # 2. IMAGE (Pollinations)
        with st.spinner("Generating Image..."):
            img_url = get_image_url(user_prompt)
            
            with col1:
                # Display the image
                st.image(img_url, caption="Generated by Pollinations (Flux)", use_container_width=True)
                
                # Fetch image data for download
                img_data = download_image(img_url)
                
                if img_data:
                    # THE DOWNLOAD BUTTON
                    st.download_button(
                        label="⬇️ Download Image",
                        data=img_data,
                        file_name="generated_poster.jpg",
                        mime="image/jpeg"
                    )
                else:
                    # Fallback if download fails
                    st.link_button("⬇️ Open Image Link", img_url)
            
            st.success("✅ Image Ready")
